name: tickets_kokosai_jp
description: ""
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core: ^4.0.0
  cloud_firestore: ^6.0.0
  url_launcher: ^6.3.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  
  assets:
     - lib/assets/img/
  fonts:
    - family: NotoSansJP
      fonts:
        - asset: lib/assets/fonts/NotoSansJP/NotoSansJP-Thin.otf
          weight: 100
        - asset: lib/assets/fonts/NotoSansJP/NotoSansJP-Light.otf
          weight: 300
        - asset: lib/assets/fonts/NotoSansJP/NotoSansJP-Regular.otf
          weight: 400
        - asset: lib/assets/fonts/NotoSansJP/NotoSansJP-Medium.otf
          weight: 500
        - asset: lib/assets/fonts/NotoSansJP/NotoSansJP-Bold.otf
          weight: 700
        - asset: lib/assets/fonts/NotoSansJP/NotoSansJP-Black.otf
          weight: 900
